### ISSUE TITLE
Feature Request: Move Type to file - Select All

### ISSUE THREAD

**Issue by DubMatrix** [oleg-shilo/MoveTypeToFile.VSIX#1]
Is it possible to also include a 'Select All' option to move all types into a separate class? I've got an autogenerated file which includes many classes (too many to select easily with the Select option) so it would be nice to just export all types into separate files at once.

**Comment by oleg-shilo** [comment]
Yep it can be done. Will do it in the next release. Hopefully this year.

Keep in mind that you can do it even now with the select option:

![image](https://user-images.githubusercontent.com/16729806/49867509-df356700-fe5e-11e8-9cd8-3341798fcb01.png)

![image](https://user-images.githubusercontent.com/16729806/49867657-3c311d00-fe5f-11e8-93a8-15a3ca37d2bf.png)

Though there is no "Select All" option. This will be the new feature to implement.

**Comment by DubMatrix** [comment]
Yes I understand that, but when the number of classes is enormous then selecting manually is very time consuming. Also selecting via keyboard (e.g. space) doesn;t work to tick the checkboxes).

**Comment by oleg-shilo** [comment]
I though that you might know that. Suggested only just in case if you don't.

**Comment by oleg-shilo** [comment]
Done. The latest release v1.4.1 delivers the feature:

![image](https://user-images.githubusercontent.com/16729806/50154757-6894df80-031e-11e9-9cc5-f3bd8c9e6e6b.png)

**Comment by DubMatrix** [comment]
Great, thanks for quickly solving this!!
