### ISSUE TITLE
Issues with definitions on single lines types

### ISSUE THREAD

**Issue by newky2k** [oleg-shilo/MoveTypeToFile.VSIX#2]
Hi,

I using you extension, which is great btw, to process an Xamarin,iOS binding ApiDefintion and it has issues where some of the definitions are on single lines.  I'm not sure what the exact cause or trigger its but on some of the lines it removes comments which causes odds results and doesn't process correctly.

This file https://github.com/xamarin/XamarinComponents/blob/master/iOS/MaterialComponents/source/MaterialComponents/ApiDefinition.cs is what i'm looking at.

**Comment by oleg-shilo** [comment]
Sorry right now I heve no capacity to look at it but will in a week or so.

**Comment by oleg-shilo** [comment]
Sorry, it did not happen "in a week or so".

All done now - v1.4.4.0

https://marketplace.visualstudio.com/items?itemName=OlegShilo.MoveTypeToFile
https://github.com/oleg-shilo/MoveTypeToFile.VSIX/releases/tag/v1.4.4.0

**Comment by newky2k** [comment]
Thanks fella!!
