### ISSUE TITLE
Window too large 

### ISSUE THREAD

**Issue by aviatrix** [oleg-shilo/MoveTypeToFile.VSIX#3]
Hello, 
I've just found this very very very helpful extension that saved me probably few hours of work. 

I have a file with over 900 classes. ( auto generated from xsd schema)
When i open the window to move all the bottom of the window is out of the visible screen
Please consider restricting the max height of the window to 50-80% of the current screen height.

Cheers for the great extension!

**Comment by oleg-shilo** [comment]
Definitely. Good point

**Comment by oleg-shilo** [comment]
Done.
Update your VS in 10 mins or so
