### ISSUE TITLE
File Scoped Namespaces

### ISSUE THREAD

**Issue by tb-mtg** [oleg-shilo/MoveTypeToFile.VSIX#5]
Firstly, excellent extension!

However, when a file is using _[File Scoped Namespaces](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)_, after using '**Move Type ToFile**' the files are moved to the wrong folder.

Could you please fix this?

Works correctly:
```
namespace Some.Fake.Namespace {
    public class FakeClassA { }
    public class FakeClassB { }
}
```

Does not work correctly:
```
namespace Some.Fake.Namespace;

public class FakeClassA { }
public class FakeClassB { }
```

**Comment by oleg-shilo** [comment]
txs, will have a look

**Comment by oleg-shilo** [comment]
Done.
See Release v1.4.7.0

**Comment by tb-mtg** [comment]
I just tested it and works great now.  Thanks for very quick response too.

**Comment by tb-mtg** [comment]
I just tested it and works great now. Thanks for very quick response too.

**Comment by oleg-shilo** [comment]
Thank you for letting me know. Glad it is resolved now
